version: "3"

services:
  latex-processor:
    image: agentew04/latex-processor:1.3
    container_name: latex-processor
    restart: always
    ports:
      - "14730:80"
      
  aspnet-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aspnet-api
    depends_on:
      - latex-processor
    ports:
      - "21209:8080"
    volumes:
      - ./data-volume:/app/Data
    restart: always  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cra-frontend
    depends_on:
      - aspnet-api
    ports:
      - "47479:80"
    restart: always

